id: P000547
initial_creation_type: ocr
created_at: 27/03/2020
last_modified_at: 2021-12-16 15:46:09.848898
source_metadata:
  id: bdr:W942
  title: དགེ་ལྡན་ལེགས་བཤད་པདྨ་དཀར་པོའི་ཆུན་པོའི་ཆུན་པོའི་འགྲེལ་པ་ཉི་མའི་འོད་ཟེར།
  author: ''
  volumes:
    b7f4c3ecab314953868de4380627070a:
      image_group_id: I1KG14819
      title: Volume 1 of dge ldan legs bshad pad+ma dkar po'i chun po'i chun po'i
        'grel pa nyi ma'i 'od zer/
      volume_number: 1
      total_pages: 196
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
